version: "3.8"

services:
  backend:
    image: dawgdevv/taskly-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskly-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-5000}
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
    ports:
      - "${PORT:-5000}:5000"
    networks:
      - taskly_network

  frontend:
    image: dawgdevv/taskly-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:5000}
    container_name: taskly-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - taskly_network

networks:
  taskly_network:
    driver: bridge
