version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: goalflow-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGO_URI: mongodb+srv://nishantraj:nishant24@cluster0.3og4q.mongodb.net/taskdb?retryWrites=true&w=majority&appName=Cluster0
      JWT_SECRET: "202267"
      FRONTEND_URL: http://localhost:5173
    ports:
      - "5000:5000"
    networks:
      - goalflow_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    container_name: goalflow-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - goalflow_network

networks:
  goalflow_network:
    driver: bridge
    # Let Docker Compose create a new network instead of using external
